### ISSUE TITLE
Renormalization of the precipitation cascade levels after an AR iteration

### ISSUE THREAD

**Issue by mpvginde** [mpvginde/pysteps#7]
Task related to this pySTEPS issue: [332](https://github.com/pySTEPS/pysteps/issues/332)

To prevent a loss of power in the precipitation cascade levels, each level should be renormalized after an AR iteration.
However if you use a global parameters for the AR iteration, the renormalization results in a constant (in time) field.

How should we proceed?

**Comment by ladc** [comment]
The field is not exactly constant in time. There's a difference between the constant radar field and the AR-evolved + renormalized (per cascade level) radar field. 

The last image below shows the original 5' blended nowcast (leftmost image) and 2 approaches to solve the loss of power from the radar extrapolation contribution. Probably it's best to do not advect the constant field (middle image) but apply the AR2 evolution and renormalize (rightmost image)

![Image](https://github.com/mpvginde/pysteps/assets/1212574/921b24ab-cde5-47eb-b559-1937d0ec56ac)

![Image](https://github.com/mpvginde/pysteps/assets/1212574/eba7915c-8d71-4292-ba38-9e2b6c1ac835)

**Comment by ladc** [comment]
![Image](https://github.com/mpvginde/pysteps/assets/1212574/bfeda804-7a3e-48cc-8c7b-ff10f29c0701)


![Image](https://github.com/mpvginde/pysteps/assets/1212574/93a00251-6b54-41f4-9315-71f3ea37d969)

**Comment by ladc** [comment]
Another example, but this time the leftmost figure is the old version (pre Michiel's issue #6 fix)

![Image](https://github.com/mpvginde/pysteps/assets/1212574/1d2f30dc-bf1f-47db-8d14-f8a1af753ad8)

**Comment by ladc** [comment]
For completeness, here's an example of the impact of no AR2 / original AR2 / renormalized AR2 on the case discussed by Michiel in his original issue:


![Image](https://github.com/mpvginde/pysteps/assets/1212574/3f803888-8a4a-49d5-b7e8-db35018d83b0)


![Image](https://github.com/mpvginde/pysteps/assets/1212574/e9d8265b-ad9f-42c8-bab5-4dd11566ea88)
