### ISSUE TITLE
Find and implement fix for the interpolation of smallest level cascades

### ISSUE THREAD

**Issue by mpvginde** [mpvginde/pysteps#9]

**Comment by ladc** [comment]
See the comments on the issue identified in #8

**Comment by mpvginde** [comment]
Proposed solution by @mpvginde : recompose the cascade, advect, and decompose again.
This might fix the "blurring" issue due to the advection, and also reduces the number of times you have to do the advection from 21 to 2. Profit!

**Comment by mpvginde** [comment]
Fixed with commit: 84ce3e972f6c073c218486b7d611eb8c03f34f9a
